from pydantic import BaseModel, ConfigDict, Field


class BomCustomerSpec(BaseModel):
    """Customer-facing FIBC specification. Maps internally to ERP header/Bom1/Bom3 keys."""

    model_config = ConfigDict(populate_by_name=True, serialize_by_alias=True)

    product_type: str = Field(default="FIBC Bulk Bag", alias="productType")
    product_category: str = Field(default="Type A — Standard", alias="productCategory")
    construction_type: str = Field(alias="constructionType")
    body_style: str = Field(default="Standard", alias="bodyStyle")
    body_grade: str = Field(default="Standard", alias="bodyGrade")
    size_type: str = Field(default="INNER", alias="sizeType")
    length: str
    width: str
    height: str
    swl: str = "1000"
    sf_ratio: str = Field(default="5:1", alias="sfRatio")
    fabric_colour: str = Field(default="White", alias="fabricColour")
    body_gsm: str = Field(alias="bodyGsm")
    body_lami: str = Field(default="0", alias="bodyLami")
    same_fabric_for_panels: bool = Field(default=True, alias="sameFabricForPanels")
    top_gsm: str = Field(default="", alias="topGsm")
    top_lami: str = Field(default="", alias="topLami")
    bottom_gsm: str = Field(default="", alias="bottomGsm")
    bottom_lami: str = Field(default="", alias="bottomLami")
    side_gsm: str = Field(default="", alias="sideGsm")
    side_lami: str = Field(default="", alias="sideLami")
    top_type: str = Field(default="Open Top", alias="topType")
    bottom_type: str = Field(default="Flat Bottom", alias="bottomType")
    duffle_height: str = Field(default="", alias="duffleHeight")
    conical_top: str = Field(default="", alias="conicalTop")
    bottom_conical_height: str = Field(default="", alias="bottomConicalHeight")
    top_spout_type: str = Field(default="Standard", alias="topSpoutType")
    top_spout_dia: str = Field(default="", alias="topSpoutDia")
    top_spout_height: str = Field(default="", alias="topSpoutHeight")
    top_spout_gsm: str = Field(default="", alias="topSpoutGsm")
    top_spout_lami: str = Field(default="", alias="topSpoutLami")
    top_spout_count: str = Field(default="1", alias="topSpoutCount")
    top_spout_edge_hemming: bool = Field(default=False, alias="topSpoutEdgeHemming")
    bottom_spout_type: str = Field(default="Standard", alias="bottomSpoutType")
    bottom_spout_dia: str = Field(default="", alias="bottomSpoutDia")
    bottom_spout_height: str = Field(default="", alias="bottomSpoutHeight")
    bottom_spout_gsm: str = Field(default="", alias="bottomSpoutGsm")
    bottom_spout_lami: str = Field(default="", alias="bottomSpoutLami")
    bottom_spout_count: str = Field(default="1", alias="bottomSpoutCount")
    bottom_spout_edge_hemming: bool = Field(default=False, alias="bottomSpoutEdgeHemming")
    loop_enabled: bool = Field(default=True, alias="loopEnabled")
    loop_type: str = Field(default="4 lift loops", alias="loopType")
    loop_construction: str = Field(default="Cross Corner", alias="loopConstruction")
    loop_gsm: str = Field(default="40", alias="loopGsm")
    loop_length: str = Field(default="30", alias="loopLength")
    loop_width: str = Field(default="5", alias="loopWidth")
    loop_count: str = Field(default="4", alias="loopCount")
    loop_till_bottom: bool = Field(default=False, alias="loopTillBottom")
    drop_loop: bool = Field(default=False, alias="dropLoop")
    drop_loop_length: str = Field(default="", alias="dropLoopLength")
    liner_enabled: bool = Field(default=False, alias="linerEnabled")
    liner_material: str = Field(default="LD", alias="linerMaterial")
    liner_type: str = Field(default="Gusseted Liner", alias="linerType")
    liner_micron: str = Field(default="", alias="linerMicron")
    doc_pouch: bool = Field(default=False, alias="docPouch")
    doc_type: str = Field(default="A4 / Vertical Open", alias="docType")
    doc_opening: str = Field(default="Vertical Open", alias="docOpening")
    doc_length: str = Field(default="30", alias="docLength")
    doc_width: str = Field(default="22", alias="docWidth")
    doc_micron: str = Field(default="100", alias="docMicron")
    doc_unit: str = Field(default="CM", alias="docUnit")
    doc_count: str = Field(default="1", alias="docCount")
    label: bool = False
    label_length: str = Field(default="10", alias="labelLength")
    label_width: str = Field(default="8", alias="labelWidth")
    label_micron: str = Field(default="100", alias="labelMicron")
    printing: str = ""
    quantity: str
    notes: str = ""
    delivery_location: str = Field(default="", alias="deliveryLocation")
    double_fold_body: bool = Field(default=False, alias="doubleFoldBody")
    double_fold_top: bool = Field(default=False, alias="doubleFoldTop")
    double_fold_bottom: bool = Field(default=False, alias="doubleFoldBottom")
    tunnel_design: str = Field(default="", alias="tunnelDesign")
    tunnel_gsm: str = Field(default="", alias="tunnelGsm")
    tunnel_lami: str = Field(default="", alias="tunnelLami")
    top_spout_tie_gsm: str = Field(default="", alias="topSpoutTieGsm")
    top_spout_tie_size: str = Field(default="", alias="topSpoutTieSize")
    top_spout_tie_remarks: str = Field(default="", alias="topSpoutTieRemarks")
    top_spout_tie_count: str = Field(default="", alias="topSpoutTieCount")
    bottom_spout_tie_gsm: str = Field(default="", alias="bottomSpoutTieGsm")
    bottom_spout_tie_size: str = Field(default="", alias="bottomSpoutTieSize")
    bottom_spout_tie_remarks: str = Field(default="", alias="bottomSpoutTieRemarks")
    bottom_spout_tie_count: str = Field(default="", alias="bottomSpoutTieCount")
    top_iris_tie_count: str = Field(default="", alias="topIrisTieCount")
    bottom_iris_tie_count: str = Field(default="", alias="bottomIrisTieCount")
    filler_cord: bool = Field(default=False, alias="fillerCord")
    filler_cord_gpm: str = Field(default="", alias="fillerCordGpm")
    filler_cord_top: bool = Field(default=False, alias="fillerCordTop")
    filler_cord_bottom: bool = Field(default=False, alias="fillerCordBottom")
    filler_cord_body: bool = Field(default=False, alias="fillerCordBody")
    filler_cord_top_spout: bool = Field(default=False, alias="fillerCordTopSpout")
    filler_cord_bottom_spout: bool = Field(default=False, alias="fillerCordBottomSpout")
    filler_cord_buffle: bool = Field(default=False, alias="fillerCordBuffle")
    filler_cord_top_type: str = Field(default="single", alias="fillerCordTopType")
    filler_cord_bottom_type: str = Field(default="single", alias="fillerCordBottomType")
    filler_cord_body_type: str = Field(default="single", alias="fillerCordBodyType")
    filler_cord_top_spout_type: str = Field(default="single", alias="fillerCordTopSpoutType")
    filler_cord_bottom_spout_type: str = Field(default="single", alias="fillerCordBottomSpoutType")
    filler_cord_buffle_type: str = Field(default="single", alias="fillerCordBuffleType")
    thread_colour: str = Field(default="", alias="threadColour")
    thread_type: str = Field(default="", alias="threadType")
    thread_buffle_seam: str = Field(default="", alias="threadBuffleSeam")
    thread_needle: str = Field(default="Single", alias="threadNeedle")
    thread_denier: str = Field(default="3600", alias="threadDenier")
    hiracle: bool = False
    hiracle_top: bool = Field(default=False, alias="hiracleTop")
    hiracle_bottom: bool = Field(default=False, alias="hiracleBottom")
    label_tyvac: bool = Field(default=False, alias="labelTyvac")
    top_rope: bool = Field(default=False, alias="topRope")
    top_rope_type: str = Field(default="Braided Rope", alias="topRopeType")
    top_rope_gsm: str = Field(default="", alias="topRopeGsm")
    top_rope_size: str = Field(default="", alias="topRopeSize")
    top_rope_cut: str = Field(default="", alias="topRopeCut")
    top_rope_color: str = Field(default="Milky White", alias="topRopeColor")
    top_rope_count: str = Field(default="1", alias="topRopeCount")
    bottom_rope: bool = Field(default=False, alias="bottomRope")
    bottom_rope_type: str = Field(default="Braided Rope", alias="bottomRopeType")
    bottom_rope_gsm: str = Field(default="", alias="bottomRopeGsm")
    bottom_rope_size: str = Field(default="", alias="bottomRopeSize")
    bottom_rope_cut: str = Field(default="", alias="bottomRopeCut")
    bottom_rope_color: str = Field(default="Milky White", alias="bottomRopeColor")
    bottom_rope_count: str = Field(default="1", alias="bottomRopeCount")
    top_spout_rope: bool = Field(default=False, alias="topSpoutRope")
    top_spout_rope_type: str = Field(default="Braided Rope", alias="topSpoutRopeType")
    top_spout_rope_gsm: str = Field(default="", alias="topSpoutRopeGsm")
    top_spout_rope_size: str = Field(default="", alias="topSpoutRopeSize")
    top_spout_rope_color: str = Field(default="Milky White", alias="topSpoutRopeColor")
    top_spout_rope_count: str = Field(default="1", alias="topSpoutRopeCount")
    top_spout_rope_remarks: str = Field(default="", alias="topSpoutRopeRemarks")
    bottom_spout_rope: bool = Field(default=False, alias="bottomSpoutRope")
    bottom_spout_rope_type: str = Field(default="Braided Rope", alias="bottomSpoutRopeType")
    bottom_spout_rope_gsm: str = Field(default="", alias="bottomSpoutRopeGsm")
    bottom_spout_rope_size: str = Field(default="", alias="bottomSpoutRopeSize")
    bottom_spout_rope_color: str = Field(default="Milky White", alias="bottomSpoutRopeColor")
    bottom_spout_rope_count: str = Field(default="1", alias="bottomSpoutRopeCount")
    bottom_spout_rope_remarks: str = Field(default="", alias="bottomSpoutRopeRemarks")
    top_tie: bool = Field(default=False, alias="topTie")
    top_tie_gsm: str = Field(default="", alias="topTieGsm")
    top_tie_size: str = Field(default="", alias="topTieSize")
    top_tie_cut: str = Field(default="", alias="topTieCut")
    top_tie_color: str = Field(default="Milky White", alias="topTieColor")
    top_tie_count: str = Field(default="1", alias="topTieCount")
    bottom_tie: bool = Field(default=False, alias="bottomTie")
    bottom_tie_gsm: str = Field(default="", alias="bottomTieGsm")
    bottom_tie_size: str = Field(default="", alias="bottomTieSize")
    bottom_tie_cut: str = Field(default="", alias="bottomTieCut")
    bottom_tie_color: str = Field(default="Milky White", alias="bottomTieColor")
    bottom_tie_count: str = Field(default="1", alias="bottomTieCount")
    top_flap: bool = Field(default=False, alias="topFlap")
    top_flap_gsm: str = Field(default="", alias="topFlapGsm")
    top_flap_lami: str = Field(default="0", alias="topFlapLami")
    top_flap_color: str = Field(default="Milky White", alias="topFlapColor")
    top_flap_count: str = Field(default="1", alias="topFlapCount")
    bottom_flap: bool = Field(default=False, alias="bottomFlap")
    bottom_flap_gsm: str = Field(default="", alias="bottomFlapGsm")
    bottom_flap_lami: str = Field(default="0", alias="bottomFlapLami")
    bottom_flap_color: str = Field(default="Milky White", alias="bottomFlapColor")
    bottom_flap_count: str = Field(default="1", alias="bottomFlapCount")
    top_hook: bool = Field(default=False, alias="topHook")
    top_hook_gsm: str = Field(default="", alias="topHookGsm")
    top_hook_size: str = Field(default="", alias="topHookSize")
    top_hook_cut: str = Field(default="", alias="topHookCut")
    top_hook_color: str = Field(default="Milky White", alias="topHookColor")
    top_hook_count: str = Field(default="1", alias="topHookCount")
    bottom_hook: bool = Field(default=False, alias="bottomHook")
    bottom_hook_gsm: str = Field(default="", alias="bottomHookGsm")
    bottom_hook_size: str = Field(default="", alias="bottomHookSize")
    bottom_hook_cut: str = Field(default="", alias="bottomHookCut")
    bottom_hook_color: str = Field(default="Milky White", alias="bottomHookColor")
    bottom_hook_count: str = Field(default="1", alias="bottomHookCount")
    bottom_loop: bool = Field(default=False, alias="bottomLoop")
    bottom_loop_gsm: str = Field(default="", alias="bottomLoopGsm")
    bottom_loop_length: str = Field(default="", alias="bottomLoopLength")
    bottom_loop_width: str = Field(default="", alias="bottomLoopWidth")
    bottom_loop_count: str = Field(default="1", alias="bottomLoopCount")
    loop_protector: bool = Field(default=False, alias="loopProtector")
    loop_protector_type: str = Field(default="None", alias="loopProtectorType")
    loop_protector_gsm: str = Field(default="", alias="loopProtectorGsm")
    loop_protector_lami: str = Field(default="0", alias="loopProtectorLami")
    loop_protector_size: str = Field(default="", alias="loopProtectorSize")
    loop_cover: bool = Field(default=False, alias="loopCover")
    loop_cover_gsm: str = Field(default="", alias="loopCoverGsm")
    loop_cover_lami: str = Field(default="0", alias="loopCoverLami")
    loop_cover_size: str = Field(default="", alias="loopCoverSize")
    loop_cover_cut: str = Field(default="", alias="loopCoverCut")
    loop_cover_count: str = Field(default="1", alias="loopCoverCount")
    felt: bool = False
    felt_top: bool = Field(default=False, alias="feltTop")
    felt_bottom: bool = Field(default=False, alias="feltBottom")
    felt_body: bool = Field(default=False, alias="feltBody")
    felt_top_spout: bool = Field(default=False, alias="feltTopSpout")
    felt_bottom_spout: bool = Field(default=False, alias="feltBottomSpout")
    mf_web: bool = Field(default=False, alias="mfWeb")
    mf_web_top: bool = Field(default=False, alias="mfWebTop")
    mf_web_bottom: bool = Field(default=False, alias="mfWebBottom")
    mf_web_body: bool = Field(default=False, alias="mfWebBody")
    mf_web_top_spout: bool = Field(default=False, alias="mfWebTopSpout")
    mf_web_bottom_spout: bool = Field(default=False, alias="mfWebBottomSpout")
    mf_web_buffle: bool = Field(default=False, alias="mfWebBuffle")
    buffle_gsm: str = Field(default="", alias="buffleGsm")
    buffle_kind: str = Field(default="Standard", alias="buffleKind")
    inner_skin: bool = Field(default=False, alias="innerSkin")
    inner_skin_gsm: str = Field(default="", alias="innerSkinGsm")
    inner_skin_lami: str = Field(default="0", alias="innerSkinLami")
    inner_skin_extra_cut: str = Field(default="0", alias="innerSkinExtraCut")
    inner_box: bool = Field(default=False, alias="innerBox")
    inner_box_gsm: str = Field(default="", alias="innerBoxGsm")
    inner_box_lami: str = Field(default="0", alias="innerBoxLami")
    top_band: bool = Field(default=False, alias="topBand")
    top_band_gsm: str = Field(default="", alias="topBandGsm")
    top_band_size: str = Field(default="", alias="topBandSize")
    stevedore: bool = False
    stevedore_gsm: str = Field(default="", alias="stevedoreGsm")
    stevedore_size: str = Field(default="", alias="stevedoreSize")
    stevedore_count: str = Field(default="1", alias="stevedoreCount")
    stevedore_portion: str = Field(default="Length", alias="stevedorePortion")
    ancerie: bool = False
    ancerie_type: str = Field(default="PP", alias="ancerieType")
    ancerie_gsm: str = Field(default="", alias="ancerieGsm")
    ancerie_size: str = Field(default="", alias="ancerieSize")
    ancerie_att: str = Field(default="0", alias="ancerieAtt")
    ancerie_count: str = Field(default="1", alias="ancerieCount")
    ancerie_color: str = Field(default="Milky White", alias="ancerieColor")
    hose_slider: bool = Field(default=False, alias="hoseSlider")
    hose_slider_count: str = Field(default="1", alias="hoseSliderCount")
    top_petal_flap_gsm: str = Field(default="", alias="topPetalFlapGsm")
    top_petal_flap_lami: str = Field(default="0", alias="topPetalFlapLami")
    bottom_petal_flap_gsm: str = Field(default="", alias="bottomPetalFlapGsm")
    bottom_petal_flap_lami: str = Field(default="0", alias="bottomPetalFlapLami")
    belly_band1: bool = Field(default=False, alias="bellyBand1")
    belly_band1_gsm: str = Field(default="", alias="bellyBand1Gsm")
    belly_band1_size: str = Field(default="", alias="bellyBand1Size")
    belly_band2: bool = Field(default=False, alias="bellyBand2")
    belly_band2_gsm: str = Field(default="", alias="bellyBand2Gsm")
    belly_band2_size: str = Field(default="", alias="bellyBand2Size")
    top_bottom_band: bool = Field(default=False, alias="topBottomBand")
    top_bottom_band_gsm: str = Field(default="", alias="topBottomBandGsm")
    top_bottom_band_size: str = Field(default="", alias="topBottomBandSize")
    safety_band: bool = Field(default=False, alias="safetyBand")
    steve_cover: bool = Field(default=False, alias="steveCover")
    steve_cover_size: str = Field(default="", alias="steveCoverSize")
    steve_cover_length: str = Field(default="", alias="steveCoverLength")
    steve_cover_gsm: str = Field(default="", alias="steveCoverGsm")
    steve_cover_lami: str = Field(default="0", alias="steveCoverLami")
    steve_cover_count: str = Field(default="1", alias="steveCoverCount")
    fabric_patch: bool = Field(default=False, alias="fabricPatch")
    fabric_patch_gsm: str = Field(default="", alias="fabricPatchGsm")
    fabric_patch_lami: str = Field(default="0", alias="fabricPatchLami")
    inner_top: bool = Field(default=False, alias="innerTop")
    inner_top_gsm: str = Field(default="", alias="innerTopGsm")
    inner_top_lami: str = Field(default="0", alias="innerTopLami")
    inner_top_extra: str = Field(default="0", alias="innerTopExtra")
    inner_top_dia: str = Field(default="", alias="innerTopDia")
    inner_bottom: bool = Field(default=False, alias="innerBottom")
    inner_bottom_gsm: str = Field(default="", alias="innerBottomGsm")
    inner_bottom_lami: str = Field(default="0", alias="innerBottomLami")
    inner_bottom_extra: str = Field(default="0", alias="innerBottomExtra")
    inner_bottom_dia: str = Field(default="", alias="innerBottomDia")
    doc_pouch1: bool = Field(default=False, alias="docPouch1")
    doc1_type: str = Field(default="Simple", alias="doc1Type")
    doc1_opening: str = Field(default="Vertical Open", alias="doc1Opening")
    doc1_length: str = Field(default="30", alias="doc1Length")
    doc1_width: str = Field(default="22", alias="doc1Width")
    doc1_micron: str = Field(default="80", alias="doc1Micron")
    doc1_unit: str = Field(default="CMS", alias="doc1Unit")
    doc1_count: str = Field(default="1", alias="doc1Count")
    doc_pouch2: bool = Field(default=False, alias="docPouch2")
    doc2_type: str = Field(default="Simple", alias="doc2Type")
    doc2_opening: str = Field(default="Vertical Open", alias="doc2Opening")
    doc2_length: str = Field(default="30", alias="doc2Length")
    doc2_width: str = Field(default="22", alias="doc2Width")
    doc2_micron: str = Field(default="80", alias="doc2Micron")
    doc2_unit: str = Field(default="CMS", alias="doc2Unit")
    doc2_count: str = Field(default="1", alias="doc2Count")
    extra_label: bool = Field(default=False, alias="extraLabel")
    extra_label_length: str = Field(default="10", alias="extraLabelLength")
    extra_label_width: str = Field(default="8", alias="extraLabelWidth")
    extra_label_micron: str = Field(default="100", alias="extraLabelMicron")
    extra_label_count: str = Field(default="1", alias="extraLabelCount")
    extra_label1: bool = Field(default=False, alias="extraLabel1")
    extra_label1_length: str = Field(default="10", alias="extraLabel1Length")
    extra_label1_width: str = Field(default="8", alias="extraLabel1Width")
    extra_label1_micron: str = Field(default="100", alias="extraLabel1Micron")
    extra_label2: bool = Field(default=False, alias="extraLabel2")
    extra_label2_length: str = Field(default="10", alias="extraLabel2Length")
    extra_label2_width: str = Field(default="8", alias="extraLabel2Width")
    extra_label2_micron: str = Field(default="100", alias="extraLabel2Micron")
    extra_label3: bool = Field(default=False, alias="extraLabel3")
    extra_label3_length: str = Field(default="10", alias="extraLabel3Length")
    extra_label3_width: str = Field(default="8", alias="extraLabel3Width")
    extra_label3_micron: str = Field(default="100", alias="extraLabel3Micron")
    bottom_spout2: bool = Field(default=False, alias="bottomSpout2")
    bottom_spout2_dia: str = Field(default="", alias="bottomSpout2Dia")
    bottom_spout2_height: str = Field(default="", alias="bottomSpout2Height")
    bottom_spout2_gsm: str = Field(default="", alias="bottomSpout2Gsm")
    bottom_spout2_lami: str = Field(default="0", alias="bottomSpout2Lami")
    bottom_spout3: bool = Field(default=False, alias="bottomSpout3")
    bottom_spout3_dia: str = Field(default="", alias="bottomSpout3Dia")
    bottom_spout3_height: str = Field(default="", alias="bottomSpout3Height")
    bottom_spout3_gsm: str = Field(default="", alias="bottomSpout3Gsm")
    bottom_spout3_lami: str = Field(default="0", alias="bottomSpout3Lami")
    packing: str = ""
    transport: str = ""
    party_name: str = Field(default="", alias="partyName")
    cable_tie: bool = Field(default=False, alias="cableTie")
    cable_tie_count: str = Field(default="", alias="cableTieCount")
    top_velcro: bool = Field(default=False, alias="topVelcro")
    bottom_velcro: bool = Field(default=False, alias="bottomVelcro")

    # Legacy display fields kept so existing quotes still parse.
    fabric: str = "Virgin PP Woven"
    gsm: str = ""
    liner: str = ""
    loops: str = ""
    accessories: list[str] = Field(default_factory=list)
    bottom_construction: str = Field(default="", alias="bottomConstruction")
    top_construction: str = Field(default="", alias="topConstruction")


class BomLineOut(BaseModel):
    model_config = ConfigDict(populate_by_name=True, serialize_by_alias=True)

    heading: str
    gsm: str = ""
    lamination: str = ""
    colour: str = ""
    fabric_size: str = Field(default="", alias="fabricSize")
    cut_size: str = Field(default="", alias="cutSize")
    total_mtr: float | None = Field(default=None, alias="totalMtr")
    total_kg: float | None = Field(default=None, alias="totalKg")
    remarks: str = ""


class BomPreviewResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True, serialize_by_alias=True)

    lines: list[BomLineOut]
    total_kg_per_bag: float = Field(alias="totalKgPerBag")
    total_material_kg: float = Field(alias="totalMaterialKg")
    quantity: float
    construction: str
    size_type: str = Field(alias="sizeType")
    dimensions: str
    warnings: list[str] = Field(default_factory=list)
    source: str = "erp-port"


class BomPreviewRequest(BaseModel):
    specification: BomCustomerSpec


